### ISSUE TITLE
Why split the labels in AWM?

### ISSUE THREAD

**Issue by birdortyedi** [flyfeatherok/SAMSD#1]
Hello, 

First, I'd like to thank you for your great work! I try to understand what you have done in this project by following the code and paper at the same time. Have a question about AWM module.

`label0, label1, label2 = tf.split(label, [2, 4, 3], axis=-1)`

Why do you need to split the labels in AWM module? 9 labels you have at the beginning, and you sum the values of 3rd 4th 5th and 6th labels, and then use remaining 6 to create weighted mask. I could not understand that part clearly. Is this about the type of attributes of something?

Thank you!

**Comment by flyfeatherok** [comment]
> Hello,
> 
> First, I'd like to thank you for your great work! I try to understand what you have done in this project by following the code and paper at the same time. Have a question about AWM module.
> 
> `label0, label1, label2 = tf.split(label, [2, 4, 3], axis=-1)`
> 
> Why do you need to split the labels in AWM module? 9 labels you have at the beginning, and you sum the values of 3rd 4th 5th and 6th labels, and then use remaining 6 to create weighted mask. I could not understand that part clearly. Is this about the type of attributes of something?
> 
> Thank you!

You are right! The 4 labels are different hair colors, you can find them in util.py. They have the same hair area, so they can be covered with one same mask.
